name: Public Package

on:
  push:
    tags:
      - "v*.*.*"

permissions: write-all

env:
  NODE_VERSION: "18.x"

jobs:
  create-package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          always-auth: true

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish package on GH
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm publish --@rocketclimb:registry=https://npm.pkg.github.com/

      - name: Publish package on NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish
